# Form implementation generated from reading ui file 'location.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Location(object):
    def setupUi(self, Location):
        Location.setObjectName("Location")
        Location.resize(894, 660)
        self.gridLayout = QtWidgets.QGridLayout(Location)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.locationList = QtWidgets.QTableWidget(parent=Location)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.locationList.setFont(font)
        self.locationList.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.locationList.setObjectName("locationList")
        self.locationList.setColumnCount(4)
        self.locationList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        self.locationList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        self.locationList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        self.locationList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        self.locationList.setHorizontalHeaderItem(3, item)
        self.locationList.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.locationList, 0, 0, 2, 1)

        self.retranslateUi(Location)
        QtCore.QMetaObject.connectSlotsByName(Location)

    def retranslateUi(self, Location):
        _translate = QtCore.QCoreApplication.translate
        Location.setWindowTitle(_translate("Location", "Form"))
        self.locationList.setSortingEnabled(True)
        item = self.locationList.horizontalHeaderItem(0)
        item.setText(_translate("Location", "序号"))
        item = self.locationList.horizontalHeaderItem(1)
        item.setText(_translate("Location", "名称"))
        item = self.locationList.horizontalHeaderItem(2)
        item.setText(_translate("Location", "地址"))
        item = self.locationList.horizontalHeaderItem(3)
        item.setText(_translate("Location", "备注"))
