# Form implementation generated from reading ui file 'location.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Location(object):
    def setupUi(self, Location):
        Location.setObjectName("Location")
        Location.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Location)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Location)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Location)
        QtCore.QMetaObject.connectSlotsByName(Location)

    def retranslateUi(self, Location):
        _translate = QtCore.QCoreApplication.translate
        Location.setWindowTitle(_translate("Location", "Form"))
        self.label.setText(_translate("Location", "地点管理"))
