# Form implementation generated from reading ui file 'work_time.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkTime(object):
    def setupUi(self, WorkTime):
        WorkTime.setObjectName("WorkTime")
        WorkTime.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(WorkTime)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=WorkTime)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(WorkTime)
        QtCore.QMetaObject.connectSlotsByName(WorkTime)

    def retranslateUi(self, WorkTime):
        _translate = QtCore.QCoreApplication.translate
        WorkTime.setWindowTitle(_translate("WorkTime", "Form"))
        self.label.setText(_translate("WorkTime", "时间管理"))
